baseURL: 'http://example.org/'
languageCode: en-us
title: NYU Predictive Analytics Unit
theme: startbootstrap_clean_blog
canonifyurls: true
paginate: 10
copyright: Code released under the Apache 2.0 license.

params:
  DateForm: 'Jan 2, 2006'
  Description: Our Lab website
  email: 'predictiveanalytics@nyumc.org'
  #author: "Yin Aphinyanaphongs"

  postSummariesFrontPage: 8
  showReadTime: true
  customCSS:
    - <absolute path to CSS>
    - /static/css/test.css
    - <or just load it off the internet>
  social:
    - title: twitter
      url: 'https://twitter.com/nyulmc_predict'
    - title: github
      url: 'https://github.com/nyupau'

menu:
  main:
    - name: home
      url: /
      weight: -300
    - name: posts
      url: /posts/
      weight: -250
    - identifier: 'team'
      name: 'Our Team'
      url: /team/
      weight: -200

